# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua Briley's Front End Stuff
email: josh@thebrileys.com
description: My collection of front end stuff that I'll probably need from time to time.
baseurl: "/front-end-notes" # the subpath of your site, e.g. /blog
url: "http://somecallmejosh.github.io" # the base hostname & protocol for your site
twitter_username: joshuabriley
github_username:  somecallmejosh

# Build settings
markdown: kramdown
permalink: /:categories/:title
